# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFiles/addInvestment.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(419, 343)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 40, 341, 51))
        
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.nameBox = QtWidgets.QComboBox(self.centralwidget)
        self.nameBox.setGeometry(QtCore.QRect(140, 110, 241, 31))
        self.nameBox.setEditable(True)
        self.nameBox.setObjectName("nameBox")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.amountInput = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.amountInput.setGeometry(QtCore.QRect(140, 160, 241, 31))
        self.amountInput.setObjectName("amountInput")
        self.amountInput.setMaximum(1000000000)
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.joinDateInput = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.joinDateInput.setGeometry(QtCore.QRect(140, 211, 241, 31))
        self.joinDateInput.setDate(QtCore.QDate(2020, 1, 1))
        self.joinDateInput.setTime(QtCore.QTime(9, 0, 0))
        self.joinDateInput.setDisplayFormat("dd/MMMM/yyyy")
        self.joinDateInput.setObjectName("joinDateInput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 160, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(40, 280, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Investment Entry"))
        self.label_4.setText(_translate("MainWindow", "Add Investment"))
        self.label.setText(_translate("MainWindow", "Amount:"))
        self.addBtn.setText(_translate("MainWindow", "Add"))
        self.label_3.setText(_translate("MainWindow", "Join Date:"))
        self.label_5.setText(_translate("MainWindow", "Investor:"))
