# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFiles/listBuyers.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 771, 51))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.buyersTable = QtWidgets.QTableWidget(self.centralwidget)
        self.buyersTable.setGeometry(QtCore.QRect(30, 180, 771, 201))
        self.buyersTable.setObjectName("buyersTable")
        self.buyersTable.setColumnCount(8)
        self.buyersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.buyersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.buyersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.buyersTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.buyersTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.buyersTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.buyersTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.buyersTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.buyersTable.setHorizontalHeaderItem(7, item)
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(30, 110, 151, 41))
        self.addBtn.setObjectName("addBtn")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(450, 110, 151, 41))
        self.saveBtn.setObjectName("saveBtn")
        self.detailsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.detailsBtn.setGeometry(QtCore.QRect(650, 110, 151, 41))
        self.detailsBtn.setObjectName("detailsBtn")
        self.deleteBtn = QtWidgets.QPushButton(self.centralwidget)
        self.deleteBtn.setGeometry(QtCore.QRect(240, 110, 151, 41))
        self.deleteBtn.setObjectName("deleteBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "List Buyers"))
        self.label_4.setText(_translate("MainWindow", "List Buyers"))
        item = self.buyersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "S. No"))
        item = self.buyersTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.buyersTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Address"))
        item = self.buyersTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Contact"))
        item = self.buyersTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
        item = self.buyersTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sale Price"))
        item = self.buyersTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Remaining Price"))
        item = self.buyersTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Total Paid"))
        self.addBtn.setText(_translate("MainWindow", "Add Buyer"))
        self.saveBtn.setText(_translate("MainWindow", "Save Report"))
        self.detailsBtn.setText(_translate("MainWindow", "Monthly Details"))
        self.deleteBtn.setText(_translate("MainWindow", "Delete Buyer"))
