# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFiles/listInvestors.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 374)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.investorsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.investorsTable.setGeometry(QtCore.QRect(20, 150, 871, 201))
        self.investorsTable.setObjectName("investorsTable")
        self.investorsTable.setColumnCount(8)
        self.investorsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.investorsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.investorsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.investorsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.investorsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.investorsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.investorsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.investorsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.investorsTable.setHorizontalHeaderItem(7, item)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 871, 51))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(20, 80, 151, 41))
        self.addBtn.setObjectName("addBtn")
        self.deleteBtn = QtWidgets.QPushButton(self.centralwidget)
        self.deleteBtn.setGeometry(QtCore.QRect(200, 80, 151, 41))
        self.deleteBtn.setObjectName("deleteBtn")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(380, 80, 151, 41))
        self.saveBtn.setObjectName("saveBtn")
        self.detailsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.detailsBtn.setGeometry(QtCore.QRect(560, 80, 151, 41))
        self.detailsBtn.setObjectName("detailsBtn")
        self.investmentBtn = QtWidgets.QPushButton(self.centralwidget)
        self.investmentBtn.setGeometry(QtCore.QRect(740, 80, 151, 41))
        self.investmentBtn.setObjectName("investmentBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "List Investors"))
        item = self.investorsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "S. No"))
        item = self.investorsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.investorsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Address"))
        item = self.investorsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Contact"))
        item = self.investorsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Join Date"))
        item = self.investorsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Total Balance"))
        item = self.investorsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Total Profit"))
        item = self.investorsTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Total Investment"))
        self.label_4.setText(_translate("MainWindow", "List Investors"))
        self.addBtn.setText(_translate("MainWindow", "Add Investor"))
        self.deleteBtn.setText(_translate("MainWindow", "Delete Investor"))
        self.saveBtn.setText(_translate("MainWindow", "Save Report"))
        self.detailsBtn.setText(_translate("MainWindow", "Monthly Details"))
        self.investmentBtn.setText(_translate("MainWindow", "Add Investment"))
